spring.application.name=auth-api

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

#spring.datasource.password=31416
#spring.datasource.username=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

internal.token=${INTERNAL_TOKEN}
jwt.secret=${JWT_SECRET}
#internal.token=my_password_is_so_secret
server.servlet.context-path=/api



